# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    volumes:
      - /Users/natchen/Documents/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
